{
 "title": "WINJECT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "LLC Packet & State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "wifi1.llc_pkt_recv",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "llc_pkt_recv{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_recv",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "llc_pkt_recv{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.llc_pkt_sent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "llc_pkt_sent{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_sent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "llc_pkt_sent{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.llc_pkt_resent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "llc_pkt_resent{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_resent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "llc_pkt_resent{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.llc_pkt_recv p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_recv{job=\"wifi1\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.llc_pkt_sent p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_sent{job=\"wifi1\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_recv p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_recv{job=\"wifi2\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_sent p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_sent{job=\"wifi2\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.llc_pkt_resent p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_resent{job=\"wifi1\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.txrx_state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "llc_tx_enabled{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.llc_pkt_resent p/s (5s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(llc_pkt_resent{job=\"wifi2\"}[5s])",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.txrx_state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "llc_tx_enabled{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    }
   ]
  },
  { "title": "LLC Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "wifi1.llc_bytes_recv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "llc_bytes_recv{job=\"wifi1\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_recv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "llc_bytes_recv{job=\"wifi2\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "llc_bytes_sent{job=\"wifi1\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "llc_bytes_sent{job=\"wifi2\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_resent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "llc_bytes_resent{job=\"wifi1\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_resent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "llc_bytes_resent{job=\"wifi2\"}",
     "legendFormat": "{{job}}/{{lcid}}"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_recv b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_recv{job=\"wifi1\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_recv{job=\"wifi1\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_sent b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_sent{job=\"wifi1\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_sent{job=\"wifi1\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_recv b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_recv{job=\"wifi2\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_recv{job=\"wifi2\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_sent b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_sent{job=\"wifi2\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_sent{job=\"wifi2\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_resent b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_resent{job=\"wifi1\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_resent{job=\"wifi1\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi1.llc_bytes_tx_total b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(llc_bytes_resent{job=\"wifi1\"}[5s])*8)+sum(rate(llc_bytes_sent{job=\"wifi1\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_resent b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(llc_bytes_resent{job=\"wifi2\"}[5s])*8",
     "legendFormat": "{{job}}/{{lcid}}"
    },
    {
     "expr": "sum(rate(llc_bytes_resent{job=\"wifi2\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi2.llc_bytes_tx_total b/s (5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(llc_bytes_resent{job=\"wifi2\"}[5s])*8)+sum(rate(llc_bytes_sent{job=\"wifi2\"}[5s])*8)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "wifi1.txrx_state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "llc_tx_enabled{job=\"wifi1\"}",
     "legendFormat": "{{job}}/{{lcid}}_tx"
    },
    {
     "expr": "llc_rx_enabled{job=\"wifi1\"}",
     "legendFormat": "{{job}}/{{lcid}}_rx"
    }
   ]
  },
  {
   "title": "wifi2.txrx_state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "llc_tx_enabled{job=\"wifi2\"}",
     "legendFormat": "{{job}}/{{lcid}}_tx"
    },
    {
     "expr": "llc_rx_enabled{job=\"wifi2\"}",
     "legendFormat": "{{job}}/{{lcid}}_rx"
    }
   ]
  },
  {
   "title": "PDCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "wifi1.pdcp_rx_reorder_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pdcp_rx_reorder_size{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi1.pdcp_tx_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pdcp_tx_queue_size{job=\"wifi1\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.pdcp_rx_reorder_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pdcp_rx_reorder_size{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    },
    {
     "title": "wifi2.pdcp_tx_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pdcp_tx_queue_size{job=\"wifi2\"}",
       "legendFormat": "{{job}}/{{lcid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "wifi1.txs_tick_error_avg46",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "txs_tick_error_avg46{job=\"wifi1\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "wifi1.txs_tick_error (2s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(txs_tick_error{job=\"wifi1\"}[2s])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "wifi2.txs_tick_error_avg46",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "txs_tick_error_avg46{job=\"wifi2\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "wifi2.txs_tick_error (2s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(txs_tick_error{job=\"wifi2\"}[2s])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}