#!/bin/sh

if [ "$#" -eq 0 ]; then
    echo "video_send <instance> <lcid> <dev_id> <width> <height> <bitrate>" 
    #                    1         2      3        4        5        6
    exit
fi

tx_port=${1}${2}1
rx_port=${1}${2}2

while :
do
    dev=$(v4l2-ctl --list-devices | grep -A1 "$3" | egrep -o "/dev/.*")
    gst-launch-1.0 -v v4l2src device=$dev ! jpegdec ! video/x-raw,width=$4,height=$5,framerate=30/1 ! x264enc tune=zerolatency bitrate=$6 ! rtph264pay ! udpsink host=127.0.0.1 port=$tx_port
done