#!/bin/sh

if [ "$#" -eq 0 ]; then
    echo "video_send <instance> <lcid> <device> <width> <height> <bitrate>" 
    #                    1         2      3        4        5        6
    exit
fi

tx_port=${1}${2}1
rx_port=${1}${2}2

gst-launch-1.0 -v v4l2src device=/dev/$3 ! jpegdec ! video/x-raw,width=$4,height=$5,framerate=30/1 ! x264enc tune=zerolatency bitrate=$6 ! rtph264pay ! udpsink host=127.0.0.1 port=$tx_port